name: muuri_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^2.4.0
  firebase_core: ^3.3.0
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^5.3.0
  google_fonts: ^6.2.1
  syncfusion_flutter_pdfviewer: ^26.2.11
  url_launcher: ^6.3.0
  firebase_auth: ^5.2.0
  provider: ^6.1.2
  loader_overlay: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # ENVIROMENT
    - .env
    
    # ASSETS
    - assets/logo-google-developer.png
    - assets/profile.png
    - assets/bg-top-login.png
    - assets/bot.png

   

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
